
stencil_serial: stencil_serial.cpp
	icpc -o stencil_serial stencil_serial.cpp -Wall -Wextra -I/opt/local/include/ -L/opt/local/lib -lopencv_core -lopencv_highgui -lm

clean:
	rm -f *.o stencil_serial
	
.PHONY: clean
